services:
  courses.api:
    image: ${DOCKER_REGISTRY-}coursesapi
    container_name: courses.api
    build:
      context: ..
      dockerfile: Courses/src/Courses.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ./cert:/https:ro
    depends_on:
     - courses.db
    networks:
     - courses-net


  courses.client:
    image: ${DOCKER_REGISTRY-}coursesclient
    build:
      context: src/client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - courses.api
    networks:
     - courses-net
  
  courses.db:
    image: postgres:latest
    container_name: courses.db
    restart: always
    environment:
      - POSTGRES_DB=courses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    networks:
     - courses-net

networks:
  courses-net:
    driver: bridge